
#ifndef _MQTTUSERCONFIG_H
#define _MQTTUSERCONFIG_H

#define MQTT_TASK

#define MQTT_TASK_NAME_DEFAULT		"MQTTTask"
#define MQTT_TASK_PRIORITY_DEFAULT	98
#define MQTT_TASK_STACKSIZE_DEFAULT	8192

#define MQTT_CLIENT
#define MQTT_SERVER

#endif
